name: Build with MySQL

on:
  push:
    branches: [ "master" ]
      #- main  # 빌드를 원하는 브랜치로 변경하세요

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: boardtest
          MYSQL_USER: your_mysql_user
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # 자신의 프로젝트에 맞는 Java 버전으로 변경하세요
        distribution: 'zulu'
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    - name: Save test reports as artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: /home/runner/work/blogManagement/blogManagement/build/reports/tests/test  # 테스트 리포트가 저장된 경로에 맞게 수정
    - name: Download test reports
      uses: actions/download-artifact@v2
      with:
        name: test-reports
        path: /C:\Users\User\Desktop\나무발발이  # 저장한 artifacts가 다운로드될 경로에 맞게 수정
      
      env:
        DB_HOST: localhost
        DB_USER: root
        DB_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        DB_NAME: boardtest
